#version: 2.1
#
#jobs:
#  build:
#    docker:
#      - image: circleci/openjdk:11-jdk
#    steps:
#      - checkout
#      - run:
#          name: Build with Maven
#          command: mvn clean install
#      - run:
#          name: Run Unit Tests
#          command: mvn test
#
#workflows:
#  version: 2
#  build_and_test:
#    jobs:
#      - build

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0
    steps:
      - checkout

      # Cache dependencies to speed up builds
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Run tests with coverage
      - run:
          name: Run tests and generate coverage report
          command: mvn clean verify

      # Save test results to be accessible in CircleCI
      - store_test_results:
          path: target/surefire-reports

      # Save coverage report as an artifact
      - store_artifacts:
          path: target/site/jacoco
          destination: coverage-reports

  # Optional: Deploy to Codecov (requires CODECOV_TOKEN env variable)
  upload_coverage:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Upload coverage to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN

workflows:
  version: 2
  test:
    jobs:
      - build
      - upload_coverage:
          requires:
            - build
