version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run tests and generate coverage report
          command: mvn clean verify

      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  test:
    jobs:
      - build
      - upload_coverage:
          requires:
            - build



