version: 2.1

jobs:
  build:
    docker:
      - image: circleci/maven:3.6.3-jdk-11
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run Unit Tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
